version: '3'
services:
  frontend:
    image: sportspace-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      BACKEND_URL: http://sportspace-api:8080
